# Generated by Django 5.1.11 on 2026-07-27 05:42

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('college_code', models.CharField(blank=True, max_length=50, null=True)),
                ('college_name', models.CharField(max_length=200)),
                ('university', models.CharField(blank=True, max_length=200, null=True)),
                ('college_type', models.CharField(blank=True, max_length=50, null=True)),
                ('college_stream', models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('arts_science', 'Arts & Science'), ('other', 'Other')], default='other', max_length=50, null=True)),
                ('status', models.CharField(default='active', max_length=20)),
                ('state', models.CharField(blank=True, choices=[('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra')], default='Tamil Nadu', max_length=100, null=True)),
                ('district', models.CharField(blank=True, choices=[('Ariyalur', 'Ariyalur'), ('Chengalpattu', 'Chengalpattu'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Cuddalore', 'Cuddalore'), ('Dharmapuri', 'Dharmapuri'), ('Dindigul', 'Dindigul'), ('Erode', 'Erode'), ('Kallakurichi', 'Kallakurichi'), ('Kanchipuram', 'Kanchipuram'), ('Kanyakumari', 'Kanyakumari'), ('Karur', 'Karur'), ('Krishnagiri', 'Krishnagiri'), ('Madurai', 'Madurai'), ('Mayiladuthurai', 'Mayiladuthurai'), ('Nagapattinam', 'Nagapattinam'), ('Namakkal', 'Namakkal'), ('Nilgiris', 'Nilgiris'), ('Perambalur', 'Perambalur'), ('Pudukkottai', 'Pudukkottai'), ('Ramanathapuram', 'Ramanathapuram'), ('Ranipet', 'Ranipet'), ('Salem', 'Salem'), ('Sivaganga', 'Sivaganga'), ('Tenkasi', 'Tenkasi'), ('Thanjavur', 'Thanjavur'), ('Theni', 'Theni'), ('Thoothukudi', 'Thoothukudi'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Tirunelveli', 'Tirunelveli'), ('Tirupathur', 'Tirupathur'), ('Tiruppur', 'Tiruppur'), ('Tiruvallur', 'Tiruvallur'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Tiruvarur', 'Tiruvarur'), ('Vellore', 'Vellore'), ('Viluppuram', 'Viluppuram'), ('Virudhunagar', 'Virudhunagar'), ('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad'), ('Bagalkote', 'Bagalkote'), ('Belagavi', 'Belagavi'), ('Ballari', 'Ballari'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Bengaluru Urban', 'Bengaluru Urban'), ('Bidar', 'Bidar'), ('Chamarajanagar', 'Chamarajanagar'), ('Chikkaballapur', 'Chikkaballapur'), ('Chikkamagaluru', 'Chikkamagaluru'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Hassan', 'Hassan'), ('Kodagu', 'Kodagu'), ('Kolar', 'Kolar'), ('Mandya', 'Mandya'), ('Mysuru', 'Mysuru'), ('Shivamogga', 'Shivamogga'), ('Tumakuru', 'Tumakuru'), ('Udupi', 'Udupi'), ('Anakapalli', 'Anakapalli'), ('Anantapur', 'Anantapur'), ('Chittoor', 'Chittoor'), ('East Godavari', 'East Godavari'), ('Eluru', 'Eluru'), ('Guntur', 'Guntur'), ('Kadapa', 'Kadapa'), ('Kakinada', 'Kakinada'), ('Krishna', 'Krishna'), ('Kurnool', 'Kurnool'), ('Nandyal', 'Nandyal'), ('Nellore', 'Nellore'), ('Prakasam', 'Prakasam'), ('Srikakulam', 'Srikakulam'), ('Visakhapatnam', 'Visakhapatnam'), ('Vizianagaram', 'Vizianagaram'), ('West Godavari', 'West Godavari'), ('Adilabad', 'Adilabad'), ('Hyderabad', 'Hyderabad'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Mahabubnagar', 'Mahabubnagar'), ('Medak', 'Medak'), ('Nalgonda', 'Nalgonda'), ('Nizamabad', 'Nizamabad'), ('Rangareddy', 'Rangareddy'), ('Warangal', 'Warangal'), ('Ahmednagar', 'Ahmednagar'), ('Aurangabad', 'Aurangabad'), ('Kolhapur', 'Kolhapur'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Pune', 'Pune'), ('Sangli', 'Sangli'), ('Satara', 'Satara'), ('Solapur', 'Solapur'), ('Thane', 'Thane')], max_length=100, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('website', models.URLField(blank=True, null=True)),
                ('college_logo', models.ImageField(blank=True, null=True, upload_to='college_logos/')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'verbose_name': 'College',
                'verbose_name_plural': 'Colleges',
                'ordering': ['college_name'],
            },
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('category', models.CharField(choices=[('Programming', 'Programming'), ('Mathematics', 'Mathematics'), ('Physics', 'Physics'), ('Soft Skills', 'Soft Skills')], max_length=100)),
                ('duration', models.CharField(max_length=20)),
                ('description', models.TextField(blank=True)),
                ('video_file', models.FileField(upload_to='videos/')),
                ('thumbnail', models.ImageField(upload_to='thumbnails/')),
                ('status', models.CharField(choices=[('Published', 'Published'), ('Draft', 'Draft')], default='Published', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('views', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='Principal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('principal_name', models.CharField(max_length=150)),
                ('principal_email', models.EmailField(max_length=254, unique=True)),
                ('principal_mobile', models.CharField(max_length=15)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('username', models.CharField(blank=True, max_length=100, null=True, unique=True)),
                ('password', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='principals', to='studentapp.college')),
            ],
            options={
                'ordering': ['principal_name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dept_code', models.CharField(max_length=20, unique=True)),
                ('dept_name', models.CharField(max_length=150)),
                ('dept_short_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('hod_name', models.CharField(max_length=150)),
                ('hod_email', models.EmailField(max_length=254, unique=True)),
                ('hod_phone', models.CharField(blank=True, max_length=15)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='departments', to='studentapp.college')),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_departments', to='studentapp.principal')),
            ],
            options={
                'ordering': ['dept_name'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(blank=True, max_length=15)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('year', models.CharField(choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], max_length=10)),
                ('username', models.CharField(max_length=100, unique=True)),
                ('password', models.CharField(max_length=100)),
                ('join_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='studentapp.college')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='studentapp.department')),
            ],
            options={
                'ordering': ['full_name'],
            },
        ),
        migrations.CreateModel(
            name='VideoWatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='studentapp.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='studentapp.video')),
            ],
            options={
                'ordering': ['-watched_at'],
                'unique_together': {('student', 'video')},
            },
        ),
    ]
