# Generated by Django 4.2.23 on 2026-07-27 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='videowatch',
            name='watched_seconds',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
