# Generated by Django 5.1.11 on 2026-07-13 11:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_alter_college_options_alter_department_college_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='college',
            options={'ordering': ['college_name'], 'verbose_name': 'College', 'verbose_name_plural': 'Colleges'},
        ),
        migrations.AlterModelOptions(
            name='department',
            options={'ordering': ['dept_name']},
        ),
        migrations.AlterModelOptions(
            name='principal',
            options={'ordering': ['principal_name']},
        ),
        migrations.AlterModelOptions(
            name='student',
            options={'ordering': ['full_name']},
        ),
        migrations.AlterModelOptions(
            name='video',
            options={'ordering': ['-uploaded_at']},
        ),
        migrations.AddField(
            model_name='video',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='department',
            name='hod_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='year',
            field=models.CharField(choices=[('I', 'First Year'), ('II', 'Second Year'), ('III', 'Third Year'), ('IV', 'Fourth Year')], max_length=10),
        ),
        migrations.CreateModel(
            name='VideoWatch',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('watched_at', models.DateTimeField(auto_now_add=True)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='studentapp.student')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='watch_history', to='studentapp.video')),
            ],
            options={
                'ordering': ['-watched_at'],
            },
        ),
    ]
