# Generated by Django 4.2.23 on 2026-07-30 10:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0002_videowatch_watched_seconds'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='video',
            options={},
        ),
        migrations.AddField(
            model_name='video',
            name='is_admin_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='video',
            name='uploaded_by_hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='videos', to='studentapp.department'),
        ),
    ]
