# Generated by Django 5.1.11 on 2026-07-13 11:46

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_college_options_alter_department_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videowatch',
            name='watched_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
