# Generated by Django 4.2.23 on 2026-07-31 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0003_alter_video_options_video_is_admin_video_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='cover_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
