# Generated by Django 4.2.23 on 2026-07-31 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0004_principal_avatar_principal_bio_principal_cover_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='department',
            name='avatar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='cover_photo',
            field=models.TextField(blank=True, null=True),
        ),
    ]
