# Generated by Django 5.1.11 on 2026-07-14 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0005_remove_student_profile_pic_student_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='principal',
            name='password',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='principal',
            name='username',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
