# Generated by Django 4.2.30 on 2026-08-10 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_alter_student_college_alter_student_department_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='otp_attempts',
            field=models.IntegerField(default=0),
        ),
    ]
