# Generated by Django 5.1.11 on 2026-07-21 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0007_college_address_college_college_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='college_stream',
            field=models.CharField(blank=True, choices=[('engineering', 'Engineering'), ('arts_science', 'Arts & Science'), ('other', 'Other')], default='other', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='join_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('expired', 'Expired')], default='active', max_length=20),
        ),
    ]
