# Generated by Django 5.1.11 on 2026-07-23 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0009_videowatch_unique_student_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='college',
            name='district',
            field=models.CharField(blank=True, choices=[('Ariyalur', 'Ariyalur'), ('Chengalpattu', 'Chengalpattu'), ('Chennai', 'Chennai'), ('Coimbatore', 'Coimbatore'), ('Cuddalore', 'Cuddalore'), ('Dharmapuri', 'Dharmapuri'), ('Dindigul', 'Dindigul'), ('Erode', 'Erode'), ('Kallakurichi', 'Kallakurichi'), ('Kanchipuram', 'Kanchipuram'), ('Kanyakumari', 'Kanyakumari'), ('Karur', 'Karur'), ('Krishnagiri', 'Krishnagiri'), ('Madurai', 'Madurai'), ('Mayiladuthurai', 'Mayiladuthurai'), ('Nagapattinam', 'Nagapattinam'), ('Namakkal', 'Namakkal'), ('Nilgiris', 'Nilgiris'), ('Perambalur', 'Perambalur'), ('Pudukkottai', 'Pudukkottai'), ('Ramanathapuram', 'Ramanathapuram'), ('Ranipet', 'Ranipet'), ('Salem', 'Salem'), ('Sivaganga', 'Sivaganga'), ('Tenkasi', 'Tenkasi'), ('Thanjavur', 'Thanjavur'), ('Theni', 'Theni'), ('Thoothukudi', 'Thoothukudi'), ('Tiruchirappalli', 'Tiruchirappalli'), ('Tirunelveli', 'Tirunelveli'), ('Tirupathur', 'Tirupathur'), ('Tiruppur', 'Tiruppur'), ('Tiruvallur', 'Tiruvallur'), ('Tiruvannamalai', 'Tiruvannamalai'), ('Tiruvarur', 'Tiruvarur'), ('Vellore', 'Vellore'), ('Viluppuram', 'Viluppuram'), ('Virudhunagar', 'Virudhunagar'), ('Alappuzha', 'Alappuzha'), ('Ernakulam', 'Ernakulam'), ('Idukki', 'Idukki'), ('Kannur', 'Kannur'), ('Kasaragod', 'Kasaragod'), ('Kollam', 'Kollam'), ('Kottayam', 'Kottayam'), ('Kozhikode', 'Kozhikode'), ('Malappuram', 'Malappuram'), ('Palakkad', 'Palakkad'), ('Pathanamthitta', 'Pathanamthitta'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Thrissur', 'Thrissur'), ('Wayanad', 'Wayanad'), ('Bagalkote', 'Bagalkote'), ('Belagavi', 'Belagavi'), ('Ballari', 'Ballari'), ('Bengaluru Rural', 'Bengaluru Rural'), ('Bengaluru Urban', 'Bengaluru Urban'), ('Bidar', 'Bidar'), ('Chamarajanagar', 'Chamarajanagar'), ('Chikkaballapur', 'Chikkaballapur'), ('Chikkamagaluru', 'Chikkamagaluru'), ('Dakshina Kannada', 'Dakshina Kannada'), ('Davanagere', 'Davanagere'), ('Dharwad', 'Dharwad'), ('Hassan', 'Hassan'), ('Kodagu', 'Kodagu'), ('Kolar', 'Kolar'), ('Mandya', 'Mandya'), ('Mysuru', 'Mysuru'), ('Shivamogga', 'Shivamogga'), ('Tumakuru', 'Tumakuru'), ('Udupi', 'Udupi'), ('Anakapalli', 'Anakapalli'), ('Anantapur', 'Anantapur'), ('Chittoor', 'Chittoor'), ('East Godavari', 'East Godavari'), ('Eluru', 'Eluru'), ('Guntur', 'Guntur'), ('Kadapa', 'Kadapa'), ('Kakinada', 'Kakinada'), ('Krishna', 'Krishna'), ('Kurnool', 'Kurnool'), ('Nandyal', 'Nandyal'), ('Nellore', 'Nellore'), ('Prakasam', 'Prakasam'), ('Srikakulam', 'Srikakulam'), ('Visakhapatnam', 'Visakhapatnam'), ('Vizianagaram', 'Vizianagaram'), ('West Godavari', 'West Godavari'), ('Adilabad', 'Adilabad'), ('Hyderabad', 'Hyderabad'), ('Karimnagar', 'Karimnagar'), ('Khammam', 'Khammam'), ('Mahabubnagar', 'Mahabubnagar'), ('Medak', 'Medak'), ('Nalgonda', 'Nalgonda'), ('Nizamabad', 'Nizamabad'), ('Rangareddy', 'Rangareddy'), ('Warangal', 'Warangal'), ('Ahmednagar', 'Ahmednagar'), ('Aurangabad', 'Aurangabad'), ('Kolhapur', 'Kolhapur'), ('Mumbai', 'Mumbai'), ('Nagpur', 'Nagpur'), ('Nashik', 'Nashik'), ('Pune', 'Pune'), ('Sangli', 'Sangli'), ('Satara', 'Satara'), ('Solapur', 'Solapur'), ('Thane', 'Thane')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='college',
            name='state',
            field=models.CharField(blank=True, choices=[('Tamil Nadu', 'Tamil Nadu'), ('Kerala', 'Kerala'), ('Karnataka', 'Karnataka'), ('Andhra Pradesh', 'Andhra Pradesh'), ('Telangana', 'Telangana'), ('Maharashtra', 'Maharashtra')], default='Tamil Nadu', max_length=100, null=True),
        ),
    ]
