# Generated by Django 5.1.11 on 2026-07-23 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('studentapp', '0011_student_date_of_birth'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_id',
        ),
    ]
